### ISSUE TITLE
Update Current Node Set

### ISSUE THREAD

**Issue by ctcncgr** [legumeinfo/DSCensor#1]
Update the nodes with the current LIS datastore BUSCOs.

**Comment by ctcncgr** [comment]
genome_main and gene_models_main objects have been loaded into the existing graph database.

https://dscensor.legumeinfo.org/

**Comment by ctcncgr** [comment]
Reopening to remind myself to do this tomorrow after a datastore-metadata update from @adf-ncgr.

**Comment by ctcncgr** [comment]
@adf-ncgr should be good. Let me know.

**Comment by adf-ncgr** [comment]
Yes looks good thanks for taking care of it On Feb 17, 2023, at 3:27 PM, Connor Cameron ***@***.***> wrote:﻿
@adf-ncgr should be good. Let me know.
