### ISSUE TITLE
SoyBase DSCensor Error

### ISSUE THREAD

**Issue by jd-campbell** [legumeinfo/DSCensor#4]
Hello:

On the dev.soybase.org website (https://dev.soybase.org/resources/annotation_stats/) there is an error where the user can not choose a species of glycine for DSCensor.  I am not sure what is missing or wrong but there is no stats or BUSCOs on the page.

**Comment by adf-ncgr** [comment]
Thanks @jd-campbell looks like the problem is on our end, affecting dscensor.legumeinfo.org (which this site has iframe'd) only with respect to annotation stats, not genome stats. @ctcncgr and I will try to sort it out ASAP!

**Comment by jd-campbell** [comment]
@adf-ncgr & @ctcncgr 
thank you for looking in it. 
ASAP is not required- dev.soybase.org is not live yet.

**Comment by adf-ncgr** [comment]
true, but dscensor.legumeinfo.org is live and has the same issue...

**Comment by ctcncgr** [comment]
This should be fixed. Thanks for reporting the issue.

**Comment by adf-ncgr** [comment]
thanks @ctcncgr !

**Comment by ctcncgr** [comment]
I'm going to close this. Please reopen if the issue remains.
